import Head from 'next/head';
import dynamic from 'next/dynamic';

import styles from './chat.module.css';

const AsyncAIChat = dynamic(() => import('@/packages/assistant-ui-chat').then(def => def.AIChat), {
  ssr: false,
  loading: () => <>loading...</>,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AsyncAIChat />
      </main>
    </>
  );
}
