import Head from 'next/head';
import dynamic from 'next/dynamic';

import styles from '@/styles/Home.module.css';

async function loadAIChat() {
  const { AIChat } = await import('@/packages/assistant-ui-chat');
  return AIChat;
}

const AsyncAIChat = dynamic(loadAIChat, {
  loading: () => <>Loading...</>,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AsyncAIChat />
      </main>
    </>
  );
}
